swagger: "2.0"
info:
  title: beego Test API
  description: |
    beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /login/logout:
    get:
      tags:
      - login
      description: |-
        Logs out current logged in user session
        <br>
      operationId: LoginController.logout
      responses:
        "200":
          description: '{string} logout success'
  /login/logout1:
    get:
      tags:
      - login
      description: |-
        Logs1 out current logged in user session
        <br>
      operationId: LoginController.logout1
      responses:
        "200":
          description: '{string} logout1 success'
tags:
- name: login
  description: |
    Operations about Users
